import type { Metadata } from "next";
import "./globals.css";
import { josefin_sans, lato_regular } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefin_sans} ${lato_regular}`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
